### ISSUE TITLE
Include merge profiles in installer

### ISSUE THREAD

**Issue by tstavrianos** [halgari/wabbajack#17]
**Is your feature request related to a problem? Please describe.**
I the modlist creator has zEdit installed in his tool folder, the merges.json of the current zEdit profile is not included and the settings.json file has the wrong paths setup.

**Describe the solution you'd like**
Apply the same workflow as the one applied to modorganizer.ini, ie: copy the files and fix the paths to point to the new installation directory.

**Comment by krageon** [comment]
Rather than implementing specific config support it would be nice to have it detect potential config files and give you the option to include them, or alternatively (as I can imagine that's actually quite slow) just have you give in additional paths. For autodetection you could give a folder to scan for candidates (e.g. the tools subdirectory) to save on traversal time.

**Comment by tstavrianos** [comment]
If we want it to be generic, it could support .ini, .cfg and .json as a start (maybe .yaml/.yml in case any apps use it).
